project:
  type: website

website:
  title: "SMiG Lab"
  favicon: imgs/smig-lab-favicon.png  
  page-footer: 
    background: light
    left: |
      ![](/imgs/smig-logo-square.png){width=20%}
      Statistical Modeling in Genoa
    right: "DIMA - Dipartimento di Matematica, Università degli Studi di Genova"
  navbar:
    logo: imgs/smig-logo-small.png
    logo-alt: "Statistical Modeling in Genoa"
    left:
      - href: index.qmd
        text: Home
      - events.qmd
      - href: people.qmd
        text: People
      - text: "Research & co."
        menu:
          - research.qmd
          - teaching.qmd
          - other.qmd
          - publications.qmd
      - about.qmd
  # margin-header: |
  #   ![Statistical Modelling in Genoa](/imgs/smig-logo-square.png)
  # margin-footer: | 
  #   DIMA - Dipartimento di Matematica\
  #   Università degli Studi di Genova\
  #   Via Dodecaneso 35 16146 Genova (GE)

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
  



