---
execute:
  echo: false
  output: true
  eval: true
---

People working in this area

```{r}
#| output: false

# Look for definition of smig.person() and format.smig.person() in:
source("people.R")

# !!NOTE: by default `former = FALSE` and `dima = !former`. Explicitly set if necessary.
people = list(
  # example generic entry
  # smig.person("Name", "Surname", dima = FALSE, phd = FALSE, former = FALSE
  #             role = "...", affiliation = "...", email = "...", website = "...")
  # current members
  smig.person("Claudia", "Fassino", role = "Researcher"),
  smig.person("Eva", "Riccomagno", role = "Ordinary Professor"),
  smig.person("Francesco", "Porro", role = "Associate Professor"),
  smig.person("Sara", "Sommariva", role = "Researcher"),
  smig.person("Muhammad", "Shoaib", phd = TRUE),
  smig.person("Marco", "Bressan", phd = TRUE),
  smig.person("Stefano", "Braccini", role = "Research fellow",
              email = "5597473@studenti.unige.it"),
  # former members
  smig.person("Maria Piera", "Rogantin", former = TRUE),
  smig.person("Ivano", "Repetto", former = TRUE),
  smig.person("Federico", "Carli", affiliation = "Axpo Italia",  former = TRUE),
  smig.person("Elena", "Pesce", affiliation = "AXA XL",  former = TRUE),
  smig.person("Giacomo", "Siri", affiliation = "Dompé",  former = TRUE),
  smig.person("Eleonora", "Saggini", role = "Math Teacher",
              affiliation = "Gastaldi-Abba",  former = TRUE),
  smig.person("Virginia", "Pirino", role = "senior analytics specialist",
              affiliation = "Costa Crociere",  former = TRUE),
  smig.person("Piotr", "Zwiernik", role = "associate professor",
              affiliation = "Toronto University",  former = TRUE),
  smig.person("Gherardo", "Varando", former = TRUE),
  smig.person("Giacomo", "Lancia", role = "post-doc",
              affiliation = "Università La Sapienza, Roma",  former = TRUE),
  smig.person("Giulia", "Bertagnolli", role = "Jr Assistant Professor",
              affiliation = "Free University of Bozen-Bolzano",  former = TRUE),
  smig.person("Jack Storror", "Carter",
              affiliation = "Utopia Fellow Universitat Pompeu Fabra", former = TRUE),
  smig.person("Orlando", "Marigliano",
              role = "Marie Skłodowska-Curie Fellow, post-doc Chalmers",
              affiliation = "Gothemburg",  former = TRUE)
)
former.idx <- which(unname(sapply(people, \(x) x["former"] == "TRUE")))
```

## Current

```{r}
#| output: asis
cat(paste(" - ", sapply(people[-former.idx], format.smig.person), collapse = "\n"))
```


## Former


```{r}
#| output: asis
cat(paste(" - ", sapply(people[former.idx], format.smig.person), collapse = "\n"))
```
